# Simple tokenizer

In [1]:
from pathlib import Path

path: Path = Path("/home/daniel/Documents/Repositorios/build-a-large-language-model/capitulo_2/The_Verdict.txt")

with open(file=path, mode="r", encoding="utf-8") as file:
    content_file = file.read()

In [2]:
content_file

'The Verdict\n\n\n\t\t\t\t\tEdith Wharton\n\n\n\n\n\n1908\n\n\n\n\n\nExported from Wikisource on May 8, 2026\n\n\n\n\n\nI HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me be

In [3]:
import re

text: str = "Hola mundo!. Esto es una prueba, pero en español."
list_text_elements: list[str] = re.split(pattern=r'(\s|[\\^$.,|?!*+()\[\]{}])', string=text)
list_text_elements

['Hola',
 ' ',
 'mundo',
 '!',
 '',
 '.',
 '',
 ' ',
 'Esto',
 ' ',
 'es',
 ' ',
 'una',
 ' ',
 'prueba',
 ',',
 '',
 ' ',
 'pero',
 ' ',
 'en',
 ' ',
 'español',
 '.',
 '']

In [4]:
list_text_elements = [elem for elem in list_text_elements if elem not in [" ", ""]]
list_text_elements

['Hola',
 'mundo',
 '!',
 '.',
 'Esto',
 'es',
 'una',
 'prueba',
 ',',
 'pero',
 'en',
 'español',
 '.']

In [5]:
# Palabras (letras/números) o símbolos específicos
# \w+ captura palabras completas.
# [\\^$.,|?!*+()\[\]{}] captura los símbolos uno a uno.
pattern = r"[^\W_]+|[.,|?!*+\[\]{}'\"():;]+"
content_file_cleaned = re.findall(pattern, content_file, re.UNICODE)
content_file_cleaned

['The',
 'Verdict',
 'Edith',
 'Wharton',
 '1908',
 'Exported',
 'from',
 'Wikisource',
 'on',
 'May',
 '8',
 ',',
 '2026',
 'I',
 'HAD',
 'always',
 'thought',
 'Jack',
 'Gisburn',
 'rather',
 'a',
 'cheap',
 'genius',
 'though',
 'a',
 'good',
 'fellow',
 'enough',
 'so',
 'it',
 'was',
 'no',
 'great',
 'surprise',
 'to',
 'me',
 'to',
 'hear',
 'that',
 ',',
 'in',
 'the',
 'height',
 'of',
 'his',
 'glory',
 ',',
 'he',
 'had',
 'dropped',
 'his',
 'painting',
 ',',
 'married',
 'a',
 'rich',
 'widow',
 ',',
 'and',
 'established',
 'himself',
 'in',
 'a',
 'villa',
 'on',
 'the',
 'Riviera',
 '.',
 '(',
 'Though',
 'I',
 'rather',
 'thought',
 'it',
 'would',
 'have',
 'been',
 'Rome',
 'or',
 'Florence',
 '.)',
 '"',
 'The',
 'height',
 'of',
 'his',
 'glory',
 '"',
 'that',
 'was',
 'what',
 'the',
 'women',
 'called',
 'it',
 '.',
 'I',
 'can',
 'hear',
 'Mrs',
 '.',
 'Gideon',
 'Thwing',
 'his',
 'last',
 'Chicago',
 'sitter',
 'deploring',
 'his',
 'unaccountable',
 'abdicat

In [6]:
set(content_file_cleaned)

{'!"',
 'suddenly',
 'Monte',
 'complex',
 'often',
 'while',
 'whole',
 'mighty',
 'irony',
 'A',
 'possessed',
 'apparent',
 'heart',
 'wanted',
 'word',
 'To',
 'exquisitely',
 'paled',
 'instructive',
 'new',
 'answered',
 'contended',
 'Why',
 'Are',
 'footstep',
 'brings',
 'effect',
 'been',
 'raised',
 'deploring',
 'morbidly',
 'sitters',
 'object',
 'happened',
 'domain',
 'lips',
 'fingers',
 'look',
 'beard',
 'weeks',
 've',
 'tells',
 'smiling',
 'too',
 '[',
 'choice',
 'furrowed',
 'up',
 'want',
 'pictures',
 'hand',
 'terrace',
 'room',
 'mine',
 'My',
 'elegant',
 'piece',
 'How',
 'distribute',
 'truth',
 'going',
 'accuse',
 'atmosphere',
 'enlightenment',
 'straight',
 'close',
 'timorously',
 'attention',
 'free',
 'vindicated',
 'trade',
 'simplifications',
 'ah',
 'stroke',
 'bear',
 'fewer',
 'constantly',
 '(',
 'shirked',
 '.)',
 'think',
 'egregious',
 'minutes',
 'page',
 'corrected',
 'full',
 'studio',
 'As',
 'denied',
 'In',
 'balustraded',
 'has',
 'h

In [7]:
all_worlds = sorted(set(content_file_cleaned))
all_worlds

['!',
 '!"',
 '"',
 '":',
 '";',
 '"?',
 "'",
 "'?",
 '(',
 ')',
 '),',
 '*',
 ',',
 ',"',
 '.',
 '."',
 ".'",
 '.)',
 '...',
 '.]',
 '0',
 '1',
 '1908',
 '1931',
 '2026',
 '4',
 '8',
 ':',
 ';',
 '?',
 '?"',
 "?'",
 'A',
 'About',
 'Ah',
 'Among',
 'And',
 'Are',
 'Arrt',
 'As',
 'At',
 'Attribution',
 'Be',
 'Begin',
 'Burlington',
 'But',
 'By',
 'Carlo',
 'Chicago',
 'Claude',
 'Come',
 'Commons',
 'Creative',
 'Croft',
 'Destroyed',
 'Devonshire',
 'Don',
 'Dubarry',
 'During',
 'Edith',
 'Emperors',
 'Exported',
 'FDL',
 'Florence',
 'For',
 'GNU',
 'Gallery',
 'Gideon',
 'Gisburn',
 'Gisburns',
 'Grafton',
 'Greek',
 'Grindle',
 'Grindles',
 'HAD',
 'Had',
 'Hang',
 'Has',
 'He',
 'Her',
 'Hermia',
 'His',
 'How',
 'I',
 'If',
 'In',
 'It',
 'Jack',
 'January',
 'Jove',
 'Just',
 'Lord',
 'Made',
 'May',
 'Miss',
 'Money',
 'Monte',
 'Moon',
 'Mr',
 'Mrs',
 'My',
 'Never',
 'No',
 'Now',
 'Nutley',
 'Of',
 'Oh',
 'On',
 'Once',
 'Only',
 'Or',
 'Perhaps',
 'Poor',
 'Professional

In [8]:
vocab_size = len(all_worlds)
vocab_size

1237

In [9]:
vocab_dictionary: dict = {content: index for index, content in enumerate(all_worlds)}
vocab_dictionary

{'!': 0,
 '!"': 1,
 '"': 2,
 '":': 3,
 '";': 4,
 '"?': 5,
 "'": 6,
 "'?": 7,
 '(': 8,
 ')': 9,
 '),': 10,
 '*': 11,
 ',': 12,
 ',"': 13,
 '.': 14,
 '."': 15,
 ".'": 16,
 '.)': 17,
 '...': 18,
 '.]': 19,
 '0': 20,
 '1': 21,
 '1908': 22,
 '1931': 23,
 '2026': 24,
 '4': 25,
 '8': 26,
 ':': 27,
 ';': 28,
 '?': 29,
 '?"': 30,
 "?'": 31,
 'A': 32,
 'About': 33,
 'Ah': 34,
 'Among': 35,
 'And': 36,
 'Are': 37,
 'Arrt': 38,
 'As': 39,
 'At': 40,
 'Attribution': 41,
 'Be': 42,
 'Begin': 43,
 'Burlington': 44,
 'But': 45,
 'By': 46,
 'Carlo': 47,
 'Chicago': 48,
 'Claude': 49,
 'Come': 50,
 'Commons': 51,
 'Creative': 52,
 'Croft': 53,
 'Destroyed': 54,
 'Devonshire': 55,
 'Don': 56,
 'Dubarry': 57,
 'During': 58,
 'Edith': 59,
 'Emperors': 60,
 'Exported': 61,
 'FDL': 62,
 'Florence': 63,
 'For': 64,
 'GNU': 65,
 'Gallery': 66,
 'Gideon': 67,
 'Gisburn': 68,
 'Gisburns': 69,
 'Grafton': 70,
 'Greek': 71,
 'Grindle': 72,
 'Grindles': 73,
 'HAD': 74,
 'Had': 75,
 'Hang': 76,
 'Has': 77,
 'He': 78

In [10]:
class SimpleTokenizerV1:

    def __init__(self, vocab_dictionary: dict) -> None:

        self._pattern = r"[^\W_]+|[.,|?!*+\[\]{}'\"():;]+"

        self.vocab_dictionary = vocab_dictionary
        self.int_to_str = {index: content for content, index in vocab_dictionary.items()}

    def encode(self, text_content: str) -> list[int]:

        content_file_cleaned: list[str] = re.findall(
            pattern=self._pattern, 
            string=text_content,
            flags=re.UNICODE
        )

        return [self.vocab_dictionary[elem] for elem in content_file_cleaned]

    def decode(self, id_content: str) -> list[str]:

        text = " ".join([self.int_to_str[_id] for _id in id_content])
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

In [11]:
tokenizer: SimpleTokenizerV1 = SimpleTokenizerV1(vocab_dictionary=vocab_dictionary)
text: str = "It's the last he painted, you know, Mrs. Gisburn said with pardonable pride."
list_ids: list[int] = tokenizer.encode(text_content=text)
list_ids

[86,
 6,
 946,
 1089,
 672,
 601,
 830,
 12,
 1233,
 666,
 12,
 99,
 14,
 68,
 947,
 1214,
 839,
 882,
 14]

In [12]:
decoded_text: list[str] = tokenizer.decode(id_content=list_ids)
decoded_text

"It' s the last he painted, you know, Mrs. Gisburn said with pardonable pride."

In [13]:
len(vocab_dictionary)

1237

# Tokenizer with unknown tokens

In [14]:
class SimpleTokenizerV2:

    def __init__(self, vocab_dictionary: dict) -> None:

        self._pattern = r"[^\W_]+|[.,|?!*+\[\]{}'\"():;]+"

        self._special_tokens: list[str] = sorted(
            {
                "<|unk|>",  
                "<|endoftext|>" 
            }
        )

        self.vocab_dictionary = self._add_special_tokens(
            vocab_dictionary=vocab_dictionary
        )

        self.int_to_str = {index: content for content, index in self.vocab_dictionary.items()}

    def _add_special_tokens(self, vocab_dictionary: dict) -> dict:

        copy_vocab_dictionary = vocab_dictionary.copy()

        for token in self._special_tokens:
            copy_vocab_dictionary.update({token: len(copy_vocab_dictionary)})

        return copy_vocab_dictionary

    def encode(self, text_content: str) -> list[int]:

        content_file_cleaned: list[str] = re.findall(
            pattern=self._pattern, 
            string=text_content,
            flags=re.UNICODE
        )

        return [self.vocab_dictionary.get(elem, self.vocab_dictionary["<|unk|>"]) for elem in content_file_cleaned] + [self.vocab_dictionary["<|endoftext|>"]]

    def decode(self, id_content: str) -> list[str]:

        text = " ".join([self.int_to_str[_id] for _id in id_content])
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

In [15]:
tokenizer: SimpleTokenizerV2 = SimpleTokenizerV2(vocab_dictionary=vocab_dictionary)
list(tokenizer.vocab_dictionary.items())[-4:]

[('your', 1235),
 ('yourself', 1236),
 ('<|endoftext|>', 1237),
 ('<|unk|>', 1238)]

In [16]:
text: str = "It's the last he painted, you know, Mrs. Gisburn said with pardonable pride."
list_ids_encode_v2: list[int] = tokenizer.encode(text_content=text)
list_ids_encode_v2

[86,
 6,
 946,
 1089,
 672,
 601,
 830,
 12,
 1233,
 666,
 12,
 99,
 14,
 68,
 947,
 1214,
 839,
 882,
 14,
 1237]

In [17]:
text: str = "It's the last he, esto es simplemente una prueba."
list_ids_encode_unk_v2: list[int] = tokenizer.encode(text_content=text)
list_ids_encode_unk_v2

[86, 6, 946, 1089, 672, 601, 12, 1238, 1238, 1238, 1238, 1238, 14, 1237]

In [18]:
list_ids_decode_unk_v2: list[str] = tokenizer.decode(id_content=list_ids_encode_unk_v2)
list_ids_decode_unk_v2

"It' s the last he, <|unk|> <|unk|> <|unk|> <|unk|> <|unk|>. <|endoftext|>"

# Byte Pair Encoding

In [19]:
import tiktoken

tokenizer_bpe = tiktoken.get_encoding(encoding_name="gpt2")

In [20]:
text: str = (
    "Hola, esto es una prueba! <|endoftext|> Hoy hace frio."
)
list_ids_tiktoken = tokenizer_bpe.encode(text=text, allowed_special={"<|endoftext|>"})
list_ids_tiktoken

[39,
 5708,
 11,
 1556,
 78,
 1658,
 555,
 64,
 778,
 518,
 7012,
 0,
 220,
 50256,
 49873,
 289,
 558,
 277,
 27250,
 13]

In [21]:
decoder_tiktoken = tokenizer_bpe.decode(tokens=list_ids_tiktoken)
decoder_tiktoken

'Hola, esto es una prueba! <|endoftext|> Hoy hace frio.'

In [23]:
text: str = "Akwirw ier"
list_ids = tokenizer_bpe.encode(text=text)
print(list_ids)
decoded_ids = tokenizer_bpe.decode(list_ids)
decoded_ids

[33901, 86, 343, 86, 220, 959]


'Akwirw ier'

# Sliding Window

In [25]:
content_file

'The Verdict\n\n\n\t\t\t\t\tEdith Wharton\n\n\n\n\n\n1908\n\n\n\n\n\nExported from Wikisource on May 8, 2026\n\n\n\n\n\nI HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me be

In [26]:
encoded_content_file_bpe = tokenizer_bpe.encode(text=content_file)
len(encoded_content_file_bpe)

5437

In [34]:
context_size : int = 4
x: list[int] = encoded_content_file_bpe[:context_size]
y: list[int] = encoded_content_file_bpe[1:context_size + 1]
print(f"x: {x}")
print(f"y:      {y}")

x: [464, 4643, 11600, 628]
y:      [4643, 11600, 628, 198]


In [35]:
for i in range(1, context_size + 1):
    context = encoded_content_file_bpe[:i]
    next_token = encoded_content_file_bpe[i]
    print(f"{context} --> {next_token}") 

[464] --> 4643
[464, 4643] --> 11600
[464, 4643, 11600] --> 628
[464, 4643, 11600, 628] --> 198


In [40]:
for i in range(1, context_size + 1):
    content = tokenizer_bpe.decode(tokens=encoded_content_file_bpe[:i])
    next_word = tokenizer_bpe.decode(tokens=[encoded_content_file_bpe[i]])
    print(f"{content} --> {next_word}")

The -->  Ver
The Ver --> dict
The Verdict --> 


The Verdict

 --> 



# Data loader

In [42]:
import torch
from torch.utils.data import Dataset, DataLoader
from tiktoken.core import Encoding

In [52]:
class GPTDatasetV1(Dataset):

    def __init__(self, text: str, tokenizer: Encoding, max_length: int, stride: int) -> None:
        """_summary_

        Args:
            text (str): Texto a tokenizar.
            tokenizer (Encoding): Tokenizador.
            max_length (int): Longitud máxima de cada fila del dataset (N X M),
                N es el numero de input, M la longitud del input, pues max_length es M.
            stride (int): Tamaño de paso entre secuencias de IDs.
        """

        self.input_ids: list[int] = []
        self.target_ids: list[int] = []

        list_tokens: list[int] = tokenizer.encode(text=text)

        for index in range(0, len(list_tokens) - max_length, stride):
            input_chunk: list[int] = list_tokens[index:index + max_length]
            target_chunk: list[int] = list_tokens[index + 1:index + 1 + max_length]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self) -> int:
        return len(self.input_ids)

    def __getitem__(self, index: int) -> tuple[int, ...]:
        return self.input_ids[index], self.target_ids[index]

In [53]:
def create_data_loader_v1(
    text: str,
    batch_size: int = 4,
    max_lenght: int = 256,
    stride: int = 128,
    shuffle: bool = True,
    drop_last: bool = True,
    num_workers: int = 0
) -> DataLoader:

    tokenizer = tiktoken.get_encoding("gpt2")
    
    dataset = GPTDatasetV1(
        text=text,
        tokenizer=tokenizer,
        max_length=max_lenght,
        stride=stride
    )

    return DataLoader(
        dataset=dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

In [74]:
dataloader = create_data_loader_v1(
    text=content_file,
    batch_size=1,
    max_lenght=4,
    stride=50,
    shuffle=False
)

In [75]:
data_iter = iter(dataloader) # parejas de input + target, tuples
first_batch = next(data_iter)
second_batch = next(data_iter)
first_batch, second_batch

([tensor([[  464,  4643, 11600,   628]]),
  tensor([[ 4643, 11600,   628,   198]])],
 [tensor([[  257,  7026, 15632,   438]]),
  tensor([[ 7026, 15632,   438,  2016]])])

# Embedding

In [113]:
input_tensor: torch.Tensor = torch.tensor([1,2,3,4])
input_tensor

tensor([1, 2, 3, 4])

In [101]:
embedding_dim: int = 3
vocab_size: int = 6
embedding_layer: torch.Tensor = torch.nn.Embedding(
    num_embeddings=vocab_size,
    embedding_dim=embedding_dim
)

In [102]:
embedding_layer.weight

Parameter containing:
tensor([[-1.1995,  0.2622,  0.4569],
        [ 0.6154,  0.8960, -0.2708],
        [-0.0732, -0.4295, -1.5246],
        [-0.6364,  0.6635, -1.4159],
        [-1.0023,  0.9285,  1.9874],
        [-0.6275,  0.3935,  0.5952]], requires_grad=True)

In [115]:
# EL embedding es una tabla look-up
# Tiene indices entre 0 - 5 (su vocabulario es 6)
# el índice 0 dará el vector [-1.1995,  0.2622,  0.4569]
# y el indice 5 dará [-0.6275,  0.3935,  0.5952]
print(embedding_layer(torch.tensor([0])))
embedding_layer(torch.tensor([5]))

tensor([[-1.1995,  0.2622,  0.4569]], grad_fn=<EmbeddingBackward0>)


tensor([[-0.6275,  0.3935,  0.5952]], grad_fn=<EmbeddingBackward0>)

In [116]:
embedding_layer(input_tensor)

tensor([[ 0.6154,  0.8960, -0.2708],
        [-0.0732, -0.4295, -1.5246],
        [-0.6364,  0.6635, -1.4159],
        [-1.0023,  0.9285,  1.9874]], grad_fn=<EmbeddingBackward0>)

# Text embedding

In [117]:
len(encoded_content_file_bpe)

5437

In [118]:
vocab_size = 50257
output_dim = 256
token_embedding_layer: torch.Tensor = torch.nn.Embedding(
    num_embeddings=vocab_size,
    embedding_dim=output_dim
)

In [119]:
max_length = 4
dataloader = create_data_loader_v1(
    text=content_file,
    batch_size=8,
    max_lenght=max_length,
    stride=max_length,
    shuffle=False
)
data_iter = iter(dataloader)
first_batch = next(data_iter)
first_batch

[tensor([[  464,  4643, 11600,   628],
         [  198,   197,   197,   197],
         [  197,   197,  7407,   342],
         [  854, 41328,   628,   628],
         [  198,   198,  1129,  2919],
         [  628,   628,   198,   198],
         [ 3109,  9213,   422, 11145],
         [  271,  1668,   319,  1737]]),
 tensor([[ 4643, 11600,   628,   198],
         [  197,   197,   197,   197],
         [  197,  7407,   342,   854],
         [41328,   628,   628,   198],
         [  198,  1129,  2919,   628],
         [  628,   198,   198,  3109],
         [ 9213,   422, 11145,   271],
         [ 1668,   319,  1737,   807]])]

In [120]:
inputs, targets = first_batch
inputs, targets

(tensor([[  464,  4643, 11600,   628],
         [  198,   197,   197,   197],
         [  197,   197,  7407,   342],
         [  854, 41328,   628,   628],
         [  198,   198,  1129,  2919],
         [  628,   628,   198,   198],
         [ 3109,  9213,   422, 11145],
         [  271,  1668,   319,  1737]]),
 tensor([[ 4643, 11600,   628,   198],
         [  197,   197,   197,   197],
         [  197,  7407,   342,   854],
         [41328,   628,   628,   198],
         [  198,  1129,  2919,   628],
         [  628,   198,   198,  3109],
         [ 9213,   422, 11145,   271],
         [ 1668,   319,  1737,   807]]))

In [ ]:
token_embedding = token_embedding_layer(inputs)
token_embedding.shape # 8 elementos, que tienen 4 tokens IDs, de 256 dimensiones

torch.Size([8, 4, 256])

In [125]:
context_lenght = max_length
positional_embedding_layer = torch.nn.Embedding(
    num_embeddings=context_lenght,
    embedding_dim=output_dim
)
positional_embedding = positional_embedding_layer(torch.arange(context_lenght))
positional_embedding.shape

torch.Size([4, 256])

In [126]:
input_embeddings = token_embedding + positional_embedding
input_embeddings.shape

torch.Size([8, 4, 256])